name: ci-deploy-prod

on:
  # Triggers the workflow on push events only.
  push:
    # Production deploys happen only when a commit has the git tag "latest".
    # We check for branch "main" below; see line 20.
    tags:
      - 'latest'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy to prod env"
    runs-on: ubuntu-latest
    environment:
      name: production
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Trigger instance refresh
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name ${{ secrets.AWS_AUTOSCALING_GROUP_NAME }} \
            --preferences '{"InstanceWarmup": 120, "MinHealthyPercentage": 30}'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
